# Generated by Django 2.2.2 on 2019-08-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='Productos/%Y')),
                ('descripcion', models.CharField(max_length=900)),
                ('titulo', models.CharField(max_length=30)),
                ('estado', models.CharField(choices=[('PEDIDO', 'pedido'), ('PROCESO', 'proceso'), ('FINALIZADO', 'finalizado')], default='RESCATADO', max_length=15)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
