# Generated by Django 2.2.2 on 2019-08-30 22:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_producto_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
