# Generated by Django 2.2.2 on 2019-08-30 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190830_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='precio',
            new_name='precioVenta',
        ),
    ]
