# Generated by Django 2.2.2 on 2019-08-30 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190830_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precioVenta',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
