# Generated by Django 2.2.3 on 2019-09-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190830_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='Productos/%Y')),
                ('descripcion', models.CharField(max_length=900)),
                ('titulo1', models.CharField(max_length=900)),
                ('descripcion1', models.CharField(max_length=900)),
                ('titulo2', models.CharField(max_length=900)),
                ('descripcion2', models.CharField(max_length=900)),
            ],
        ),
    ]
