# Generated by Django 2.2.2 on 2019-09-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20190905_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='de',
            field=models.CharField(default='Nombre', max_length=900),
        ),
    ]
