# Generated by Django 2.2.3 on 2019-09-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20190906_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='de',
            field=models.CharField(default='', max_length=900),
        ),
    ]
