# Generated by Django 2.2.2 on 2019-09-07 01:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20190906_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='total',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
