# Generated by Django 2.2.2 on 2019-09-07 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_reserva_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='total',
        ),
    ]
