# Generated by Django 2.2.2 on 2019-09-07 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_remove_reserva_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
